services:
  postgres:
    image: postgres:16-alpine
    container_name: library_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: library_db
    ports:
      - "55433:5432"
    volumes:
      - library_postgres_data:/var/lib/postgresql/data

volumes:
  library_postgres_data: