CREATE TYPE "GlobalTheme" AS ENUM (
  'DEFAULT',
  'HALLOWEEN',
  'CHRISTMAS',
  'CYBERPUNK'
);

CREATE TABLE "AppSettings" (
  "id" INTEGER NOT NULL DEFAULT 1,
  "globalTheme" "GlobalTheme" NOT NULL DEFAULT 'DEFAULT',
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updatedAt" TIMESTAMP(3) NOT NULL,

  CONSTRAINT "AppSettings_pkey" PRIMARY KEY ("id")
);
