ALTER TYPE "SocialActivityType"
ADD VALUE IF NOT EXISTS 'READING_STARTED';

ALTER TYPE "SocialActivityType"
ADD VALUE IF NOT EXISTS 'RATING_ADDED';

ALTER TABLE "SocialActivity"
ADD COLUMN IF NOT EXISTS "rating" INTEGER;